name: Build 

on:
  pull_request: 
        types: [ opened, edited, synchronize, reopened ] 

jobs:
  GithubTest:
    name: TiCS
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: TICS Action Run
        uses: tiobe/tics-github-action@main
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TICSAUTHTOKEN: ZTZiMDRmYjQtZGQzZC00YmZkLWE5YTMtNDU4MmQ3YTdiZGFlOj5DUFBrJ1kuO0pqdE1HPg
        with:
          projectName: 'cpp-game'
          ticsConfiguration: 'http://192.168.1.117:42506/tiobeweb/TICS/api/cfg?name=default'
          calc: 'CS,GATE'
